# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - msp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_96d05ed190374e1d96d33c19b4a49e71 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_866e0fca555940b5b48a0c27c9ed0712 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_96d05ed190374e1d96d33c19b4a49e71 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'msp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d1681fbd43540e6b5dd3e6443950236 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_96d05ed190374e1d96d33c19b4a49e71 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'